services:
  - type: web
    name: ai-tailor-resume-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
